### ISSUE TITLE
Multiple comments due to several votes while lagging

### ISSUE THREAD

**Issue by Ryuusei-Aika** [venix12/spotlights#27]
![image](https://user-images.githubusercontent.com/52080494/67122538-9d184700-f220-11e9-9249-70b0bc7c8596.png)

Yes let's fix this (I should've avoid fixing grammars while the site is lagging...)

**Comment by cl8n** [comment]
are you supposed to be allowed to post multiple comments at all?

**Comment by venix12** [comment]
nope
