### ISSUE TITLE
Discord is Down

### ISSUE THREAD

**Issue by Snowleopard-osu** [venix12/spotlights#30]
Discord is having server issues right now, you can reply to this when you’re ready for me to deploy the new changes though lol. Already made a local backup just in case there is issue with new code.

**Comment by venix12** [comment]
yeah please do

**Comment by Snowleopard-osu** [comment]
Oh also, you should consider tagging commits with a version number (make up however you want to do versioning), that way we can quickly switch between versions when needed

**Comment by Snowleopard-osu** [comment]
Ok last 2 commits deployed

**Comment by venix12** [comment]
will look into tagging commits soon
