### ISSUE TITLE
move & redirect osu.spotlights.team

### ISSUE THREAD

**Issue by cl8n** [venix12/spotlights#34]
to close #24 so i can turn off the original server

- [ ] permanent redirect osu.spotlights.team/ to https://spotlights.team/app
- [ ] fix osu.spotlights.team A record (192.243.101.170)
- [ ] sign cert for https

**Comment by Snowleopard-osu** [comment]
All 3 steps are completed now

**Comment by cl8n** [comment]
thanks =)
